/*core.js*/

var vocacional = ['Iformatica',
                    'Programación',
                    'Diseño',
                    'Guardaparques',
                    'Peluqueria',
                    'Inteligencia artificial',
                    'Electronica',
                    'Quimica',
                    'Mecanica',
                    'Historia',
                    'Geografia',
                    'Serigrafia',
                    'Medicina',    
                    'Enfermeria',
                    'Sociologia',
                    'Profesorado',
                    'Instructor',
                    'Buceo',    
                    'Paracaidismo',
                    'Montañismo',
                    'Alpisnimo',                    
                    'Corredor',                        
                    'Artes Marciales',
                    'Yoga',
                    'Nutrición',
                    'Educación Fisica',
                    'Economia',
                    'Administración de empresas',
                    'Abogacia',
                    'Piloto',                    
                    'Circo',
                    'Malabares',
                    'Acrobacias',
                    'Telas acrobaticas',
                    'Corte y Confección',
                    'Acrobacia de piso',
                    'Calistenia',
                    'Ping Pong',
                    'Volley',
                                        
                    'Fotografia',
                    'Musica',
                    'Arte',
                    'Pintura',
                    'Caligrafia',
                    'Mecanografia',
                    'Reparación de PC',
                    'Redes informaticas',                    
                    'Electricidad',
                    'Electrotecnia',
                    'Electromecanico',
                    
                    'Arquitectura',
                    'Caligrafia',
                    'Mecanografia',
                    'Reparación de PC',
                    'Redes informaticas'                    
                ];

var software   = ['Nube',
                    'Gestion',
                    'Compresion',
                    'Datos',
                    'Tren',
                    'Servidor',
                    'P2P',
                    'Velocidad',                    
                    'Comercio',
                    'Bancos',
                    'Seguros',
                    'Inteligencia artificial',
                    'Big Data',
                    'Turismo',
                    'Hoteles',
                    'Noticias',
                    'Analizador',
                    'Comparador',
                    'Seguros',    
                    'Canciones',
                    'Textos',
                    'Conversaciones',
                    'Google',
                    'Twitter',    
                    'Conectar',
                    'NoSql',
                    'Conversaciones'
                ];


var dataorigen = titulos = ['vida',  
                    'amor', 
                    'desiciones',
                    'sociedad', 
                    'miedo', 
                    'deseo', 
                    'destino', 
                    'simfonia',
                    'El día cero ', 
                    'Entre dos vidas', 
                    'Poema de la creación', 
                    'Te espero al amanecer', 
                    'Nadie te ha visto', 
                    'Botánica del caos', 
                    'El Sindrome',
                    'disfrutar', 
                    'degustar', 
                    'acariciar', 
                    'recorrer', 
                    'alabar',
                    'fracasar', 
                    'miedo', 
                    'dudar', 
                    'agoniza', 
                    'falacia',
                    'familia', 
                    'superpoderes', 
                    'fantasia', 
                    'magia', 
                    'extgraterrestres',
                    'paracaidas',
                    'cerca', 
                    'mata', 
                    'obtiene', 
                    'siente', 
                    'desarrolla',
                    'nene', 'nena', 'adulto', 'adolecente', 'gato', 'pajaro', 'arbol', 
                    'perro', 'roca', 'agua', 'luz', 'molecula', 'atomo', 'momia',
                    'egipcio', 'africano', 'mujer', 
                    'hombre', 'planeta', 
                    'sol', 'luna', 
                    'fantasma', 
                    'detective',
                    'boy scout', 'paracaidista', 'abogado', 'de negocios', 'tenista', 'jugador de futbol', 
                    'gigante', 'surfista', 
                    'skeateboard', 'masajista', 'profesor/a de yoga', 'profesor de gimnasia',
                    'diminuto', 'fantasma', 
                    'monstruoso/a', 'lunatico/a', 'detective', 
                    'escritor', 'youtuber', 'cineasta',
                    'actor/actriz',
                    'falta de gravedad', 
                    '2 cabezas', 		
                    'levitar', 
                    'otro mundo', 
                    'viaje en el tiempo', 
                    'cambio de sexo',				  
                    'luna sangriante', 
                    'noche eterna', 
                    'cambio de edad', 				  				  
                    'cambio de cuerpo', 
                    'mundo sin curvas', 
                    'mundo sin angulos', 
                    'mundo sin colores', 
                    'mundo con breves saltos en el tiempo',
                    'portales en el oceano',
                    'repeticion de un dia o de un momento constantemente',
                    'viaje en dimensiones',
                    'llamadas al pasado',
                    'maldicion', 
                    'libro magico', 
                    'hechizo casero', 
                    'mundo fantastico'
                   ];